// try y catch
const numero1 = 234;

try {
  console.log(numero1);
  console.log(numero2);
} catch (error) {
  console.log(`${error}`);
}
